/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedCallLogsRouteImport } from './routes/_authenticated/call-logs'
import { Route as AuthenticatedPhoneNumbersRouteImport } from './routes/_authenticated/phone-numbers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedAssistantsIndexRouteImport } from './routes/_authenticated/assistants.index'
import { Route as AuthenticatedAssistantsAssistantIdRouteImport } from './routes/_authenticated/assistants.$assistantId'
import { Route as AuthenticatedCallLogsCallIdRouteImport } from './routes/_authenticated/call-logs.$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallLogsRoute = AuthenticatedCallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhoneNumbersRoute =
  AuthenticatedPhoneNumbersRouteImport.update({
    id: '/phone-numbers',
    path: '/phone-numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantsIndexRoute =
  AuthenticatedAssistantsIndexRouteImport.update({
    id: '/assistants/',
    path: '/assistants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantsAssistantIdRoute =
  AuthenticatedAssistantsAssistantIdRouteImport.update({
    id: '/assistants/$assistantId',
    path: '/assistants/$assistantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallLogsCallIdRoute =
  AuthenticatedCallLogsCallIdRouteImport.update({
    id: '/$callId',
    path: '/$callId',
    getParentRoute: () => AuthenticatedCallLogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/call-logs': typeof AuthenticatedCallLogsRouteWithChildren
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/call-logs/$callId': typeof AuthenticatedCallLogsCallIdRoute
  '/assistants/': typeof AuthenticatedAssistantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/call-logs': typeof AuthenticatedCallLogsRouteWithChildren
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/call-logs/$callId': typeof AuthenticatedCallLogsCallIdRoute
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/call-logs': typeof AuthenticatedCallLogsRouteWithChildren
  '/_authenticated/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/_authenticated/call-logs/$callId': typeof AuthenticatedCallLogsCallIdRoute
  '/_authenticated/assistants/': typeof AuthenticatedAssistantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/api-keys'
    | '/call-logs'
    | '/phone-numbers'
    | '/settings'
    | '/tools'
    | '/assistants/$assistantId'
    | '/call-logs/$callId'
    | '/assistants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/api-keys'
    | '/call-logs'
    | '/phone-numbers'
    | '/settings'
    | '/tools'
    | '/assistants/$assistantId'
    | '/call-logs/$callId'
    | '/assistants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/api-keys'
    | '/_authenticated/call-logs'
    | '/_authenticated/phone-numbers'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/assistants/$assistantId'
    | '/_authenticated/call-logs/$callId'
    | '/_authenticated/assistants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-logs': {
      id: '/_authenticated/call-logs'
      path: '/call-logs'
      fullPath: '/call-logs'
      preLoaderRoute: typeof AuthenticatedCallLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/phone-numbers': {
      id: '/_authenticated/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/phone-numbers'
      preLoaderRoute: typeof AuthenticatedPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistants/': {
      id: '/_authenticated/assistants/'
      path: '/assistants'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AuthenticatedAssistantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistants/$assistantId': {
      id: '/_authenticated/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AuthenticatedAssistantsAssistantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-logs/$callId': {
      id: '/_authenticated/call-logs/$callId'
      path: '/$callId'
      fullPath: '/call-logs/$callId'
      preLoaderRoute: typeof AuthenticatedCallLogsCallIdRouteImport
      parentRoute: typeof AuthenticatedCallLogsRoute
    }
  }
}

interface AuthenticatedCallLogsRouteChildren {
  AuthenticatedCallLogsCallIdRoute: typeof AuthenticatedCallLogsCallIdRoute
}

const AuthenticatedCallLogsRouteChildren: AuthenticatedCallLogsRouteChildren = {
  AuthenticatedCallLogsCallIdRoute: AuthenticatedCallLogsCallIdRoute,
}

const AuthenticatedCallLogsRouteWithChildren =
  AuthenticatedCallLogsRoute._addFileChildren(
    AuthenticatedCallLogsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedCallLogsRoute: typeof AuthenticatedCallLogsRouteWithChildren
  AuthenticatedPhoneNumbersRoute: typeof AuthenticatedPhoneNumbersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedAssistantsAssistantIdRoute: typeof AuthenticatedAssistantsAssistantIdRoute
  AuthenticatedAssistantsIndexRoute: typeof AuthenticatedAssistantsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedCallLogsRoute: AuthenticatedCallLogsRouteWithChildren,
  AuthenticatedPhoneNumbersRoute: AuthenticatedPhoneNumbersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedAssistantsAssistantIdRoute:
    AuthenticatedAssistantsAssistantIdRoute,
  AuthenticatedAssistantsIndexRoute: AuthenticatedAssistantsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
